services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - '11434:11434'
    volumes:
      - models:/root/.ollama/models
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
volumes:
  models: